[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_filter = +<main.c> +<spi_display.c>
build_src_flags = -O0
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
lib_deps = 
    lvgl/lvgl

build_flags = 
    -I include
    -I src
    -I .pio/libdeps/proton
    -D LV_CONF_INCLUDE_SIMPLE

extra_scripts = pre:filter_libs.py