// Auto-generated by gen_sounds.py — DO NOT EDIT BY HAND.
// 8-bit unsigned PCM, 22050 Hz, centered at 128.
#ifndef SOUNDS_H
#define SOUNDS_H

#include <stdint.h>

#define SND_SAMPLE_RATE 22050

extern const uint8_t SND_MOVE[771];
#define SND_MOVE_LEN 771
extern const uint8_t SND_PLACE[2646];
#define SND_PLACE_LEN 2646
extern const uint8_t SND_WIN[14332];
#define SND_WIN_LEN 14332
extern const uint8_t SND_LOSE[15214];
#define SND_LOSE_LEN 15214

#endif // SOUNDS_H
